# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Waffle < Formula
  desc "Decentralized marketplace for LLM tokens"
  homepage "https://github.com/waffle-protocol/waffle"
  version "0.1.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/waffle-protocol/waffle-studio/releases/download/v0.1.2/waffle_0.1.2_darwin_amd64.tar.gz"
      sha256 "3a7c50db57081abf303bf7a5595f93499a652caf92c493b01750d0656e95f3ca"

      def install
        bin.install "waffle"
      end
    end
    on_arm do
      url "https://github.com/waffle-protocol/waffle-studio/releases/download/v0.1.2/waffle_0.1.2_darwin_arm64.tar.gz"
      sha256 "3956559f2bc14bc6ce91c0a8745c3b82b2ff9e630149ac3d5e5b583a69d7a216"

      def install
        bin.install "waffle"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/waffle-protocol/waffle-studio/releases/download/v0.1.2/waffle_0.1.2_linux_amd64.tar.gz"
        sha256 "a64a88fba0ccd17b2461954dd9c3f5565f33be2160fec743fa3862d1ab22e2ac"

        def install
          bin.install "waffle"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/waffle-protocol/waffle-studio/releases/download/v0.1.2/waffle_0.1.2_linux_arm64.tar.gz"
        sha256 "b2d7d7dc82f39901b30ff5e2099f34871b4d9d90580632f626abd93dfa5945d0"

        def install
          bin.install "waffle"
        end
      end
    end
  end

  test do
    system "#{bin}/waffle", "--help"
  end
end
