# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Waffle < Formula
  desc "Decentralized marketplace for LLM tokens"
  homepage "https://github.com/waffle-protocol/waffle"
  version "0.1.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/waffle-protocol/waffle-studio/releases/download/v0.1.3/waffle_0.1.3_darwin_amd64.tar.gz"
      sha256 "bb068ebfd734eb180354fb600df8452a792a1a8993a3d4af0da0235b7ff43ade"

      def install
        bin.install "waffle"
      end
    end
    on_arm do
      url "https://github.com/waffle-protocol/waffle-studio/releases/download/v0.1.3/waffle_0.1.3_darwin_arm64.tar.gz"
      sha256 "eedfa2ed1cdf3082d9820467a33ca7628b6429a66624aa08574e7db2be611819"

      def install
        bin.install "waffle"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/waffle-protocol/waffle-studio/releases/download/v0.1.3/waffle_0.1.3_linux_amd64.tar.gz"
        sha256 "a6f4b77914c9a02d0948a1e856649260d180d77bff3c9d239dba224201eae83f"

        def install
          bin.install "waffle"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/waffle-protocol/waffle-studio/releases/download/v0.1.3/waffle_0.1.3_linux_arm64.tar.gz"
        sha256 "bef54fc2425d05126c4904b8e285f45b7643c463e7cc96abb96e1fd8747c402e"

        def install
          bin.install "waffle"
        end
      end
    end
  end

  test do
    system "#{bin}/waffle", "--help"
  end
end
