# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Waffle < Formula
  desc "Decentralized marketplace for LLM tokens"
  homepage "https://github.com/waffle-protocol/waffle"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/waffle-protocol/waffle-studio/releases/download/v0.1.1/waffle_0.1.1_darwin_amd64.tar.gz"
      sha256 "cdbcf74682b1f83716a4ea5281ad88d68cbca8aa334fd58cb4a7d79a27a15a75"

      def install
        bin.install "waffle"
      end
    end
    on_arm do
      url "https://github.com/waffle-protocol/waffle-studio/releases/download/v0.1.1/waffle_0.1.1_darwin_arm64.tar.gz"
      sha256 "ed1a58c257e852d45501d8a3850060bf6e50b354b12df867e0309f64012cd4fd"

      def install
        bin.install "waffle"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/waffle-protocol/waffle-studio/releases/download/v0.1.1/waffle_0.1.1_linux_amd64.tar.gz"
        sha256 "333a88c04477d9441640d262ab2e32e18a2496764d98c6bf6548975fbca2682a"

        def install
          bin.install "waffle"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/waffle-protocol/waffle-studio/releases/download/v0.1.1/waffle_0.1.1_linux_arm64.tar.gz"
        sha256 "591c578616dfd7ee74c4571dbc3a2a8e0b2f17cc977563024e009fd21fddba38"

        def install
          bin.install "waffle"
        end
      end
    end
  end

  test do
    system "#{bin}/waffle", "--help"
  end
end
